baseurl = ""
title = "Siran Yao"
theme = "hugo-universal-theme"
languageCode = "zh"
hasCJKLanguage = true
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "zh"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Code highlight
pygmentsUseClasses = false
pygmentCodeFences = true
# Enable google analytics by uncomment this
googleAnalytics = "UA-93485976-2"

# Define the number of posts per page
paginate = 10

[menu]

# Main menu

[[menu.main]]
    name = "主页"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "博客"
    url  = "/blog/"
    weight = 2

[[menu.main]]
    name="文档"
    identifier = "docs"
    weight = 3

[[menu.main]]
    parent="docs"
    name="Istio官网"
    url = "https://istio.io/"
    weight = 3

    [[menu.main]]
    parent="docs"
    name="Pulsar官网"
    url = "http://pulsar.apache.org/en/"
    weight = 4


[[menu.main]]
    name = "联系我"
    url  = "/contact/"
    weight = 5
# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/servicemesher"
    pre = "<i class='fa fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 2
    name = "Twitter"
    url = "https://twitter.com/servicemesher"
    pre = "<i class='fa fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 3
    name = "Slack"
    url = "https://servicemesher.slack.com"
    pre = "<i class='fa fa-2x fa-slack'></i>"

[[menu.topbar]]
    weight = 4
    name = "Wechat"
    url = "/contact"
    pre = "<i class='fa fa-2x fa-wechat'></i>"

[[menu.topbar]]
    weight = 5
    name = "Google Group"
    url = "https://groups.google.com/forum/#!forum/servicemesher"
    pre = "<i class='fa fa-2x fa-google'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "Siran Yao(姚毅晨)"
    defaultKeywords = ["goland","pulsar","service mesh","服务网格"]
    defaultDescription = "技术分享"
    # Browser title description
    description = "技术分享"
    # Google Maps API key (if not set will default to not passing a key.)
    googleMapsApiKey = ""
    # Baidu统计
    baiduKey="154337f0d95f0b110f98c1d5d7038895"
    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
     style = "blue"
    # Social share buttons
    share = false

    # 404 page
    errorimage = "/img/404.jpg"
    email = "1061347899@qq.com"
    # about_us = "<p>Service Mesh 爱好者</br>github地址</p>"
    about_us = "<p>想当程序员的程序员</p>"
    theyann = "theyann"
    copyright = "Copyright ©️ 2020, ServiceMesher all rights reserved."
    icpno = "苏ICP备20005919号"
    # Format dates with Go's time formatting
    date_format = "2006年1月2日"
    logo = "/img/uugai.com_1583215700293.png"
    # avatar used for thumbnail on sharing
    avatar = "/img/uugai.com_1583215700293.png"
    logosmall = "/img/uugai.com_1583215700293.png"
    address = """<p>个人微信</br>请备注姓名-公司信息</p><p><img src="/img/1.png"></p>
      """
    # 是否开启评论功能
    gitalk = false

[Permalinks]
    #blog = "/blog/:year/:month/:day/:filename/"
    blog = "/blog/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = false
    text = """<p>联系方式➡</p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true
    # Set carousel background image
    # background = "https://gw.alipayobjects.com/mdn/site_comm/afts/img/A*7D3oTpL_3G0AAAAAAAAAAABjARQnAQ"
    background = "/img/blog/banners/using-opentracing-with-istio-part-1.jpg"
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = true
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = ""
    subtitle = ""

[params.see_more]
    enable = true
    icon = "fa fa-pagelines"
    title = ""
    subtitle = ""
    link_url = ""
    link_text = ""

[params.partners]
    enable = false
    # All partners are defined in their own files. You can find example items
    # at 'data/partners'.
    # For more informtion take a look at the README.
    title = "合作社区"
    subtitle = "ServiceMesher 社区合作伙伴"

[params.recent_posts]
    enable = true
    title = "最新博客"
    subtitle = ""

[outputs]
    home = ["HTML", "RSS", "Algolia"]

[outputFormats.Algolia]
    baseName = "algolia"
    isPlainText = true
    mediaType = "application/json"
    notAlternative = true

[params.algolia]
    enable = true
    appid = "X4YB3WOBNV"
    index = "servicemesher"
    vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
    params = ["categories", "tags"]
    key = "d2134c5a8d250e6d3246594240c45201"
